version: '3'
services:
  db:
    container_name: task-it
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: task-it
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
